

#' Opens a full screen map after uploading a geojson file
#'
#'Takes a gist object and a input geojson file name and renders fullscreen map
#' @param gist_object An object of class \code{gist_id} generated by \code{gist_create}
#' @param  browse Default is \code{TRUE}. Set to \code{FALSE} if you don't want to automatically browse to the URL.
#' @export
#' @importFrom assertthat assert_that has_extension
#' @examples \dontrun{
#' library(ecoengine)
#' x <- ee_observations(genus = "vulpes")
#' ee_map(x, dest = "~/Desktop")
#' gist_id <- gist_create(files = "~/Desktop/temp.geojson", browse = FALSE)
#' gist_map(gist_id)
#'
#'}
gist_map <- function(gist_object, browse = TRUE) {

    file <- names(gist_object$files)
    assertthat::assert_that(has_extension(file, "geojson"))
    render_url <- "https://render.githubusercontent.com/view/geojson/?url=https://gist.githubusercontent.com/"
    point <- length(gist_object$history)
    version <-gist_object$history[[point]]$version
    full_path <- gist_object$history[[point]]$url
    user <- gist_object$history[[point]]$user$login
    commit <- gsub("https://api.github.com/gists/", "", full_path)
    actual_commit <- strsplit(commit, "/")[[1]][1]
    path <- paste(render_url, user, actual_commit, "raw", file, sep = "/")
    if(browse) {
        browseURL(path)
    } else {
        path
    }
}
