

#' Opens a full screen map after uploading a geojson file
#'
#'Takes a gist object and a input geojson file name and renders fullscreen map
#' @param file Must be a geojson file
#' @param gist_object An object generated by \code{gist_id}
#' @param  browse Default is \code{TRUE}. Set to \code{FALSE} if you don't want to automatically browse to the URL.
#' @export
#' @import assertthat
#' @importFrom stringr str_split
#' @examples \dontrun{
#' library(ecoengine)
#' x <- ee_observations(genus = "vulpes")
#' ee_map(x, dest = "~/Desktop")
#' gist_id <- gist_create(files = "~/Desktop/temp.geojson", browse = FALSE)
#' gistr_map(file = "temp.geojson", gist_id)
#' 
#'}
gistr_map <- function(file = NULL, gist_object, browse = TRUE) {
    
    assertthat::assert_that(has_extension(file, "geojson"))

    render_url <- "https://render.githubusercontent.com/view/geojson/?url=https://gist.githubusercontent.com/"
    point <- length(gist_object$history)
    version <-gist_object$history[[point]]$version
    full_path <- gist_object$history[[point]]$url
    user <- gist_object$history[[point]]$user$login
    file_name <- names(gist_object$files)[1]
    commit <- gsub("https://api.github.com/gists/", "", full_path)
    actual_commit <- str_split(commit, "/")[[1]][1]
    path <- paste(render_url, user, actual_commit, "raw", file_name, sep = "/")
    if(browse) {
        browseURL(path)
    } else {
        path
    }
}